# Generated by Django 3.1.4 on 2021-01-07 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_auto_20210106_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='auth.user'),
        ),
    ]
